name: Python CI
on:
  pull_request:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the application
        run: |
          python3 app.py  